/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "AnswersTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "ApiRouter": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "BotApiRouter": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "QuizStateTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "Site": {
      "type": "sst.aws.StaticSite"
      "url": string
    }
    "TelegramBotToken": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "UsersTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
  }
}
